name: Quality Control

on:
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Coverage
        run: cargo llvm-cov --all-features --workspace --fail-under-lines 80

      - name: Linting
        run: cargo clippy --all-targets --all-features
